import fs from "node:fs/promises";
import path from "node:path";
import { pathToFileURL } from "node:url";
import * as esbuild from "esbuild";
import React from "react";
import { renderToStaticMarkup } from "react-dom/server";

const repoRoot = path.resolve(new URL("..", import.meta.url).pathname);
const sourcePath = path.join(repoRoot, "src/ui/Shell.jsx");
const outputPath = path.join(repoRoot, "public/index.html");
const checkOnly = process.argv.includes("--check");

async function importJsxModule(filePath) {
  const source = await fs.readFile(filePath, "utf8");
  const transformed = await esbuild.transform(source, {
    format: "esm",
    jsx: "automatic",
    loader: "jsx",
    sourcefile: filePath,
  });
  const tmpDir = path.join(repoRoot, "node_modules/.cache/codex-remote-control-lab");
  await fs.mkdir(tmpDir, { recursive: true });
  const tmpPath = path.join(tmpDir, `shell-${process.pid}-${Date.now()}.mjs`);
  await fs.writeFile(tmpPath, transformed.code, "utf8");
  try {
    return await import(pathToFileURL(tmpPath).href);
  } finally {
    await fs.rm(tmpPath, { force: true });
  }
}

function renderDocument(shell) {
  return `<!doctype html>
<html lang="ja">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Codex Remote</title>
    <link rel="icon" type="image/svg+xml" href="favicon.svg" />
    <link rel="icon" type="image/png" sizes="192x192" href="icon-192.png" />
    <link rel="apple-touch-icon" href="apple-touch-icon.png" />
    <link rel="manifest" href="site.webmanifest" />
    <meta name="theme-color" content="#15151a" />
    <link rel="stylesheet" href="/style.css" />
  </head>
  <body class="hide-artifacts">
    <!-- Generated by scripts/build-ui.mjs from src/ui/Shell.jsx. Edit the React source, not this file. -->
    ${shell}
    <script src="/main.js"></script>
  </body>
</html>
`;
}

const { CodexRemoteShell } = await importJsxModule(sourcePath);
const shell = renderToStaticMarkup(React.createElement(CodexRemoteShell));
const html = renderDocument(shell);

if (checkOnly) {
  const current = await fs.readFile(outputPath, "utf8");
  if (current !== html) {
    console.error("public/index.html is out of date. Run npm run build:ui.");
    process.exit(1);
  }
} else {
  await fs.writeFile(outputPath, html, "utf8");
  console.log(`Generated ${path.relative(repoRoot, outputPath)} from src/ui/Shell.jsx`);
}
